### ISSUE TITLE
Analytics across multiple docs

### ISSUE THREAD

**Issue by perezfr** [perezfr/crowdlaaers#22]
Ability to look across multiple docs as an aggregate. 
e.g. listing tag totals and search across multiple documents.
h/t Nate Angell

**Comment by xolotl** [comment]
Thank you @perezfr !

**Comment by perezfr** [comment]
URLs can be combined in the HAPI query.
i.e.
https://hypothes.is/api/search?limit=200&url=http://dmlcentral.net/speculative-design-for-emergent-learning-taking-risks&https://clalliance.org/blog/speculative-design-for-emergent-learning-taking-risks/

**Comment by fjperez6** [comment]
This feature was added with the release last year when updated to use Jon Udell's hlib package.
